# BEAM Chat — production image.
#
# Multi-stage build mirroring the standard Phoenix 1.8 release Dockerfile
# shape, with the plan-mandated elixir:1.19-alpine builder (plan Phase 10/11
# bump from the PRD's elixir:1.16). Build context is this directory (the
# beam_chat/ subdir of the repo root).

###########
# Builder #
###########
# ⚠️ ALPINE LOCKSTEP — this stage and the Runtime stage MUST run the same
# Alpine major version. The release is compiled against the builder's
# OpenSSL/crypto libraries; the resulting crypto NIF will NOT load on a
# different Alpine's OpenSSL (alpine:3.19 = OpenSSL 3.1.x vs alpine:3.23 =
# OpenSSL 3.5.x) — the image dies at boot with "Error relocating ...
# EVP_PKEY_sign_message_init: symbol not found" and a Kernel pid terminated
# (application_controller). Never bump one stage without the other. Verify
# they still match after any base image change with:
#   docker run --rm --entrypoint /bin/sh elixir:1.19.5-alpine -c "cat /etc/alpine-release"
#   docker run --rm --entrypoint /bin/sh alpine:3.23 -c "cat /etc/alpine-release"
# elixir:1.19.5-alpine is pinned (not elixir:1.19-alpine) because the
# floating tag would silently track a future Alpine release.
FROM elixir:1.19.5-alpine AS builder

# build-base (Erlang NIF deps), git (heroicons is a GitHub dep fetched by
# mix deps.get), nodejs+npm (npm ci for livekit-client in assets/).
RUN apk add --no-cache build-base git nodejs npm

WORKDIR /app

# Default all mix invocations to prod (mix assets.setup/assets.deploy must
# not run in dev, where dev-only deps were not fetched by deps.get --only
# prod). The explicit MIX_ENV=prod prefixes below are redundant but
# self-documenting.
ENV MIX_ENV=prod

# hex + rebar before any mix invocation
RUN mix local.hex --force && mix local.rebar --force

# Fetch prod deps only. mix.lock is required. git is installed above so the
# heroicons GitHub dep resolves. This layer only invalidates when
# mix.exs/mix.lock change.
COPY mix.exs mix.lock ./
RUN MIX_ENV=prod mix deps.get --only prod

# npm deps (prod only): livekit-client ^2.5.0 is imported by assets/js/app.js
# and resolved by esbuild via assets/node_modules. npm ci requires
# package-lock.json, which is tracked in git (see .gitignore).
COPY assets/package.json assets/package-lock.json ./assets/
RUN cd assets && npm ci --omit=dev

# Compile deps with the prod config present. Only invalidated by config/
# changes (config.exs, prod.exs).
COPY config/ ./config/
RUN MIX_ENV=prod mix deps.compile

# Install the hex-managed tailwind/esbuild binaries BEFORE copying assets/,
# mirroring the canonical phx.gen.release Dockerfile ordering: assets.setup
# does not depend on any asset files, and this way asset edits do not
# re-trigger the binary downloads (tailwind is ~115MB).
RUN mix assets.setup

# App source + static assets. priv/static raw files (favicon, robots,
# images/) are NOT regenerated by assets.deploy and must ship in the image.
COPY lib/ ./lib/
COPY priv/ ./priv/

# Compile the app BEFORE assets.deploy, mirroring the canonical
# phx.gen.release Dockerfile ordering: mix compile writes the colocated
# JavaScript manifest (_build/prod/phoenix-colocated/beam_chat/index.js)
# which esbuild resolves via NODE_PATH when bundling the
# `import {hooks} from "phoenix-colocated/beam_chat"` in assets/js/app.js.
RUN MIX_ENV=prod mix compile

# Assets. assets.setup (binaries) already ran above; assets.deploy builds +
# digests. topbar is vendored as .cjs because package.json sets
# "type": "module" (esbuild treats .js as ESM there); app.js imports it
# explicitly as ../vendor/topbar.cjs.
COPY assets/ ./assets/
RUN mix assets.deploy

# rel/ must be present so mix release evaluates rel/env.sh.eex (long-name
# distribution + RELEASE_NODE + conditional RELEASE_COOKIE export).
COPY rel/ ./rel/

# Assemble the release (compiles the app, evaluates rel/*.eex overlays
# including rel/env.sh.eex).
RUN MIX_ENV=prod mix release

###########
# Runtime #
###########
# ⚠️ ALPINE LOCKSTEP — must match the Builder stage's Alpine major version
# (see the lockstep comment above the builder FROM). The BEAM's crypto NIF
# was compiled against the builder's OpenSSL (3.5.x on alpine 3.23) and will
# not load against a different OpenSSL, killing the VM at boot with a
# relocation error. Bump both stages together — never this one alone.
FROM alpine:3.23

# libstdc++ (NIFs: bcrypt, jiffy, etc.), openssl (TLS), ncurses-libs (BEAM
# terminal), bash (release scripts). busybox wget covers the healthcheck.
RUN apk add --no-cache libstdc++ openssl ncurses-libs bash

WORKDIR /app

# Non-root runtime user (alpine syntax). The release dir is chowned so the
# BEAM can write crash dumps / any runtime files under /app.
RUN addgroup -S app && adduser -S app -G app

COPY --from=builder /app/_build/prod/rel/beam_chat ./
RUN chown -R app:app /app

USER app

# Runtime configuration (DATABASE_URL, SECRET_KEY_BASE, RELEASE_COOKIE,
# LIVEKIT_*, ...) comes from the environment at runtime; the Dockerfile only
# enables the web server. DO NOT bake secrets into the image.
ENV PHX_SERVER=true

EXPOSE 4000

HEALTHCHECK --interval=15s --timeout=5s --retries=3 \
  CMD wget -qO- http://localhost:4000/health || exit 1

ENTRYPOINT ["/app/bin/beam_chat"]
CMD ["start"]
