import Config

# Database: default credentials match `docker-compose.yml` in the repo root.
# Start Postgres with: docker compose up -d (from repo root).
# Override with DATABASE_URL, e.g. postgresql://postgres:postgres@localhost:5432/beam_chat_dev
if database_url = System.get_env("DATABASE_URL") do
  config :beam_chat, BeamChat.Repo,
    url: database_url,
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
else
  config :beam_chat, BeamChat.Repo,
    username: System.get_env("BEAMCHAT_DB_USERNAME", "beamchat_app"),
    password: System.get_env("BEAMCHAT_DB_PASSWORD", "beamchat_app"),
    hostname: "localhost",
    database: "beam_chat_dev",
    stacktrace: true,
    show_sensitive_data_on_connection_error: true,
    pool_size: 10
end

# SECURITY: the app must NOT connect as the Postgres superuser, or PostgreSQL
# Row Level Security (see CATEGORY_REDESIGN.md §9) is silently bypassed. Create
# the non-superuser role with: `mix run priv/repo/setup_app_role.exs`.

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :beam_chat, BeamChatWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "OYuufymy7keYTjHB0Ay1KryIw0rs/RpK6CzTBfGxG6ZUyxjzYBqfkKFMkFWuohTo",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:beam_chat, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:beam_chat, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :beam_chat, BeamChatWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/beam_chat_web/router\.ex$"E,
      ~r"lib/beam_chat_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :beam_chat, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Staff wallet test credits + webhook tunnel URLs (see scripts/webhook-dev.sh)
config :beam_chat, :allow_dev_wallet_credit, true

# Dev-only CSP allowlist for the Figma MCP design-capture script. Must NOT be
# set in prod.exs — leaks `https://mcp.figma.com` into the prod surface,
# widening the XSS attack surface. See SECURITY_REVIEW.md P1 #6.
config :beam_chat, :csp_dev_extras, true
